#!/bin/bash

set -x -e

#: Cleanup
rm -rf vim-rc busyna.rc
rm -rf vim-db busyna.db
rm -rf vim-rc2 busyna.rc2
rm -rf vim-make busyna.mk
rm -rf busyna.dot busyna-dot.png

if ! [ -d vim-0 ]; then
    : busyna vim-test: clone original vim to vim-0
    git clone https://github.com/vim/vim.git vim-0
    (cd vim-0; git reset --hard v7.4.1153)
fi

: busyna vim-test: Create the busyna.rc script
cp -R vim-0 vim-rc
(
cd vim-rc
sed -i '/SHELL = \/bin\/sh/d' src/Makefile
sed -i '/MAKE="$[(]MAKE[)]"/d' src/Makefile
sed -i 's/^#\s*QUOTESED\s*=.*/QUOTESED=cat/' src/Makefile
sed -i 's@\(The name of the makefile MUST .*\)(.*@\1@' src/Makefile
busyna-extract make ../busyna.rc
./src/vim --version
) 2>&1 | tee lua-rc.txt

: busyna vim-test: Test the script with shell
cp -Rl vim-0 vim-sh
(
cd vim-sh
/bin/sh ../busyna.rc
./src/vim --version
) 2>&1 | tee lua-sh.txt

: busyna vim-test: create busyna.db
cp -Rl vim-0 vim-db
(
cd vim-db
busyna-run ../busyna.rc ../busyna.db
./src/vim --version
: busyna.db created
) 2>&1 | tee lua-db.txt

: busyna vim-test: test deploying busyna.rc
busyna-deploy busyna busyna.db busyna.rc2
cp -Rl vim-0 vim-rc2
(
cd vim-rc2
mkdir src/objects
/bin/sh ../busyna.rc2
./src/vim --version
) 2>&1 | tee lua-rc2.txt

: busyna vim-test: test deploying make
busyna-deploy make busyna.db busyna.mk
cp -R vim-0 vim-make
(
cd vim-make
make -f ../busyna.mk
./src/vim --version
) 2>&1 | tee lua-make.txt

: busyna vim-test: test deploying dot
busyna-deploy dot busyna.db busyna.dot
dot -Tpdf -o busyna-dot.pdf busyna.dot 2>&1 | tee lua-dot.txt

